"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import JsBarcode from "jsbarcode";
import { api, AuditEntry, AuthResult, Barcode, Coupon, CouponInput, CouponStatus, Space } from "../lib/api";
import { Pagination } from "./Pagination";
import styles from "./CouponWithApp.module.css";

const statusLabel:Record<CouponStatus,string>={AVAILABLE:"사용 가능",CLAIMED:"선점됨",USED:"사용 완료",EXPIRED:"만료"};
const actionLabel:Record<string,string>={COUPON_CREATED:"등록",COUPON_UPDATED:"정보 수정",COUPON_CLAIMED:"선점",COUPON_RELEASED:"선점 해제",COUPON_AUTO_RELEASED:"자동 해제",COUPON_REVEALED:"바코드 열람",COUPON_USED:"사용 완료",COUPON_EXPIRED:"만료",COUPON_CORRECTED:"상태 정정",COUPON_DELETED:"삭제"};
function localInput(value:string){const date=new Date(value),local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}

export function CouponView({spaces,session,demo}:{spaces:Space[];session:AuthResult|null;demo:boolean}){
  const [spaceId,setSpaceId]=useState(spaces[0]?.id??"");const [coupons,setCoupons]=useState<Coupon[]>([]);const [status,setStatus]=useState("");const [query,setQuery]=useState("");
  const [editor,setEditor]=useState<Coupon|null|"new">(null);const [barcode,setBarcode]=useState<Barcode|null>(null);const [history,setHistory]=useState<{coupon:Coupon;entries:AuditEntry[]}|null>(null);const [correcting,setCorrecting]=useState<Coupon|null>(null);
  const [error,setError]=useState("");const [loading,setLoading]=useState(false);const [reload,setReload]=useState(0);const [page,setPage]=useState(1);const [now,setNow]=useState(()=>Date.now());const pageSize=8;
  const space=spaces.find(item=>item.id===spaceId)??spaces[0],token=session?.accessToken;

  useEffect(()=>{let active=true;async function load(){await Promise.resolve();if(!space?.id)return;setLoading(true);try{const data=demo?demoCoupons(space.id):await api.listCoupons(token!,space.id,status,query);if(active)setCoupons(data)}catch(reason){if(active)setError(reason instanceof Error?reason.message:"쿠폰을 불러오지 못했습니다.")}finally{if(active)setLoading(false)}}void load();return()=>{active=false}},[demo,query,reload,space?.id,status,token]);
  useEffect(()=>{const clock=window.setInterval(()=>setNow(Date.now()),1000);const refresh=window.setInterval(()=>setReload(value=>value+1),30000);return()=>{window.clearInterval(clock);window.clearInterval(refresh)}},[]);

  function replace(coupon:Coupon){setCoupons(current=>current.map(item=>item.id===coupon.id?coupon:item))}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!space)return;const form=new FormData(event.currentTarget);const input:CouponInput={title:String(form.get("title")),brand:String(form.get("brand")),description:String(form.get("description")),expiresAt:new Date(String(form.get("expiresAt"))).toISOString(),barcodeValue:String(form.get("barcodeValue")),barcodeFormat:String(form.get("barcodeFormat"))};try{if(demo)setEditor(null);else{if(editor==="new")await api.createCoupon(token!,space.id,input);else await api.updateCoupon(token!,(editor as Coupon).id,input);setEditor(null);setReload(value=>value+1)}}catch(reason){setError(reason instanceof Error?reason.message:"쿠폰을 저장하지 못했습니다.")}}
  async function action(coupon:Coupon,type:"claim"|"release"|"use"){try{if(demo){const claimed=type==="claim";const claimedAt=claimed?new Date().toISOString():coupon.claimedAt;replace({...coupon,status:claimed?"CLAIMED":type==="use"?"USED":"AVAILABLE",claimedBy:type==="release"?undefined:"demo",claimedByName:type==="release"?undefined:"김모아",claimedAt:type==="release"?undefined:claimedAt,claimExpiresAt:claimed?new Date(new Date(claimedAt!).getTime()+900000).toISOString():type==="release"?undefined:coupon.claimExpiresAt,barcodeAvailable:claimed});return}const changed=type==="claim"?await api.claimCoupon(token!,coupon.id):type==="release"?await api.releaseCoupon(token!,coupon.id):await api.useCoupon(token!,coupon.id);replace(changed)}catch(reason){setError(reason instanceof Error?reason.message:"쿠폰 상태를 변경하지 못했습니다.")}}
  async function reveal(coupon:Coupon){try{setBarcode(demo?{couponId:coupon.id,value:"8801234567893",format:"EAN13",status:coupon.status}:await api.revealBarcode(token!,coupon.id))}catch(reason){setError(reason instanceof Error?reason.message:"바코드를 열지 못했습니다.")}}
  async function remove(coupon:Coupon){if(!window.confirm("쿠폰을 삭제할까요?"))return;try{if(!demo)await api.deleteCoupon(token!,coupon.id);setCoupons(current=>current.filter(item=>item.id!==coupon.id))}catch(reason){setError(reason instanceof Error?reason.message:"쿠폰을 삭제하지 못했습니다.")}}
  async function showHistory(coupon:Coupon){try{const entries=demo?demoHistory(coupon):await api.couponHistory(token!,coupon.id);setHistory({coupon,entries})}catch(reason){setError(reason instanceof Error?reason.message:"쿠폰 이력을 불러오지 못했습니다.")}}
  async function correct(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!correcting)return;const form=new FormData(event.currentTarget);try{const target=String(form.get("status")) as Exclude<CouponStatus,"CLAIMED">;const reason=String(form.get("reason"));const changed=demo?{...correcting,status:target,claimedBy:undefined,claimedByName:undefined,claimedAt:undefined,claimExpiresAt:undefined,barcodeAvailable:false}:await api.correctCoupon(token!,correcting.id,target,reason);replace(changed);setCorrecting(null)}catch(reason){setError(reason instanceof Error?reason.message:"쿠폰 상태를 정정하지 못했습니다.")}}
  function claimRemaining(coupon:Coupon){if(!coupon.claimExpiresAt)return "";const seconds=Math.max(0,Math.ceil((new Date(coupon.claimExpiresAt).getTime()-now)/1000));if(seconds===0)return "자동 해제 처리 중";return `선점 남은 시간 ${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`}

  const safePage=Math.min(page,Math.max(1,Math.ceil(coupons.length/pageSize)));const visibleCoupons=coupons.slice((safePage-1)*pageSize,safePage*pageSize);
  return <section className={`${styles.card} ${styles.couponSection}`}>
    <div className={styles.sharedToolbar}><div><h2>쿠폰함</h2><p>선점은 15분 동안 유지되며 모든 상태 변경은 이력에 남습니다.</p></div>{space?.role!=="VIEWER"&&<button className={styles.primaryButton} onClick={()=>setEditor("new")}>＋ 쿠폰 등록</button>}</div>
    <div className={styles.filterBar}><select value={space?.id} onChange={event=>{setSpaceId(event.target.value);setPage(1)}}>{spaces.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="브랜드 또는 쿠폰 검색"/><select value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}><option value="">전체 상태</option>{Object.entries(statusLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
    {error&&<p className={styles.error}>{error}</p>}{loading&&<p className={styles.empty}>쿠폰을 불러오는 중…</p>}
    <div className={styles.couponGrid}>{visibleCoupons.map(coupon=><article className={styles.couponCard} key={coupon.id} data-status={coupon.status}><header><span>{coupon.brand}</span><b>{statusLabel[coupon.status]}</b></header><div className={styles.couponIcon}>◇</div><h3>{coupon.title}</h3><p>{coupon.description||"함께 사용할 수 있는 공유 쿠폰"}</p><time>{new Date(coupon.expiresAt).toLocaleString("ko-KR")}까지</time>{coupon.claimedByName&&<small>{coupon.claimedByName} 님이 선점</small>}{coupon.status==="CLAIMED"&&<strong className={styles.claimTimer}>{claimRemaining(coupon)}</strong>}<footer>{coupon.status==="AVAILABLE"&&space?.role!=="VIEWER"&&<button className={styles.primaryButton} onClick={()=>action(coupon,"claim")}>15분 선점</button>}{coupon.status==="CLAIMED"&&coupon.barcodeAvailable&&<><button onClick={()=>reveal(coupon)}>바코드 보기</button><button onClick={()=>action(coupon,"use")}>사용 완료</button><button onClick={()=>action(coupon,"release")}>선점 해제</button></>}{coupon.canEdit&&<button onClick={()=>setEditor(coupon)}>수정</button>}<button onClick={()=>showHistory(coupon)}>이력</button>{coupon.canCorrect&&<button onClick={()=>setCorrecting(coupon)}>상태 정정</button>}{coupon.canEdit&&<button className={styles.dangerButton} onClick={()=>remove(coupon)}>삭제</button>}</footer></article>)}</div>
    <Pagination page={safePage} totalItems={coupons.length} pageSize={pageSize} onChange={setPage}/>{!loading&&coupons.length===0&&<p className={styles.empty}>등록된 쿠폰이 없습니다.</p>}
    {editor&&<CouponEditor coupon={editor==="new"?null:editor} onClose={()=>setEditor(null)} onSubmit={save}/>}
    {barcode&&<BarcodeModal barcode={barcode} onClose={()=>setBarcode(null)}/>}
    {history&&<HistoryModal value={history} onClose={()=>setHistory(null)}/>}
    {correcting&&<CorrectionModal coupon={correcting} onClose={()=>setCorrecting(null)} onSubmit={correct}/>}
  </section>
}

function CouponEditor({coupon,onClose,onSubmit}:{coupon:Coupon|null;onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+30);return <div className={styles.modalBackdrop}><div className={styles.modal}><button className={styles.closeButton} onClick={onClose}>×</button><p className={styles.eyebrow}>공유 쿠폰</p><h2>{coupon?"쿠폰 수정":"쿠폰 등록"}</h2><form className={styles.form} onSubmit={onSubmit}><label>브랜드<input required name="brand" maxLength={80} defaultValue={coupon?.brand}/></label><label>쿠폰 이름<input required name="title" maxLength={120} defaultValue={coupon?.title}/></label><label>설명<input name="description" maxLength={2000} defaultValue={coupon?.description}/></label><label>만료일<input required type="datetime-local" name="expiresAt" defaultValue={localInput(coupon?.expiresAt??tomorrow.toISOString())}/></label><label>바코드 값<input required name="barcodeValue" maxLength={500} placeholder={coupon?"보안을 위해 다시 입력해 주세요":"숫자 또는 코드"}/></label><label>바코드 형식<select name="barcodeFormat" defaultValue={coupon?.barcodeFormat??"CODE128"}><option>CODE128</option><option>EAN13</option></select></label><button className={styles.primaryButtonLarge}>저장</button></form></div></div>}
function BarcodeModal({barcode,onClose}:{barcode:Barcode;onClose:()=>void}){const canvas=useRef<HTMLCanvasElement>(null);useEffect(()=>{if(!canvas.current)return;const options={width:2,height:92,margin:12,displayValue:true,fontSize:16,background:"#ffffff",lineColor:"#151515"};const format=barcode.format==="EAN13"&&/^\d{12,13}$/.test(barcode.value)?"EAN13":"CODE128";try{JsBarcode(canvas.current,barcode.value,{...options,format})}catch{JsBarcode(canvas.current,barcode.value,{...options,format:"CODE128"})}},[barcode]);return <div className={styles.modalBackdrop}><div className={`${styles.modal} ${styles.barcodeModal}`}><button className={styles.closeButton} onClick={onClose}>×</button><p className={styles.eyebrow}>선점 사용자 전용 · 열람 기록 저장됨</p><h2>쿠폰 바코드</h2><canvas ref={canvas} aria-label={`${barcode.format} 쿠폰 바코드`}/><code>{barcode.value}</code><small>{barcode.format} · 사용 후 반드시 사용 완료로 변경해 주세요.</small></div></div>}
function HistoryModal({value,onClose}:{value:{coupon:Coupon;entries:AuditEntry[]};onClose:()=>void}){return <div className={styles.modalBackdrop}><div className={`${styles.modal} ${styles.historyModal}`}><button className={styles.closeButton} onClick={onClose}>×</button><p className={styles.eyebrow}>{value.coupon.brand}</p><h2>{value.coupon.title} 이력</h2><div className={styles.auditList}>{value.entries.length===0?<p className={styles.empty}>아직 기록이 없습니다.</p>:value.entries.map(entry=><div key={entry.id}><i/><span><strong>{actionLabel[entry.action]??entry.action}</strong><small>{entry.summary}</small>{entry.reason&&<em>사유: {entry.reason}</em>}</span><time>{entry.actorName}<br/>{new Date(entry.createdAt).toLocaleString("ko-KR")}</time></div>)}</div></div></div>}
function CorrectionModal({coupon,onClose,onSubmit}:{coupon:Coupon;onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){return <div className={styles.modalBackdrop}><div className={styles.modal}><button className={styles.closeButton} onClick={onClose}>×</button><p className={styles.eyebrow}>관리자 작업 · 감사 기록 저장</p><h2>쿠폰 상태 정정</h2><p className={styles.modalDescription}>현재 상태는 <strong>{statusLabel[coupon.status]}</strong>입니다. 잘못 표시된 경우에만 정정해 주세요.</p><form className={styles.form} onSubmit={onSubmit}><label>변경 상태<select name="status" defaultValue="AVAILABLE"><option value="AVAILABLE">사용 가능</option><option value="USED">사용 완료</option><option value="EXPIRED">만료</option></select></label><label>정정 사유<textarea required name="reason" minLength={5} maxLength={500} placeholder="예: 실수로 사용 완료 처리하여 복구"/></label><button className={styles.primaryButtonLarge}>사유와 함께 정정</button></form></div></div>}

function demoCoupons(spaceId:string):Coupon[]{const expiry=new Date();expiry.setDate(expiry.getDate()+7);return[{id:"demo-coupon",spaceId,title:"아메리카노 한 잔",brand:"Moa Cafe",description:"가족 누구나 사용 가능",expiresAt:expiry.toISOString(),barcodeFormat:"EAN13",status:"AVAILABLE",ownerId:"demo",barcodeAvailable:false,canEdit:true,canCorrect:true,version:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}]}
function demoHistory(coupon:Coupon):AuditEntry[]{return[{id:"audit-demo",spaceId:coupon.spaceId,actorId:"demo",actorName:"김모아",action:"COUPON_CREATED",resourceType:"COUPON",resourceId:coupon.id,summary:`${coupon.title} 쿠폰 등록`,createdAt:coupon.createdAt}]}
