"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import JsBarcode from "jsbarcode";
import { api, AuthResult, Barcode, Coupon, CouponInput, CouponStatus, Space } from "../lib/api";
import { Pagination } from "./Pagination";
import styles from "./CouponWithApp.module.css";

const statusLabel:Record<CouponStatus,string>={AVAILABLE:"사용 가능",CLAIMED:"선점됨",USED:"사용 완료",EXPIRED:"만료"};
function localInput(value:string){const date=new Date(value),local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
export function CouponView({spaces,session,demo}:{spaces:Space[];session:AuthResult|null;demo:boolean}){
  const [spaceId,setSpaceId]=useState(spaces[0]?.id??"");const [coupons,setCoupons]=useState<Coupon[]>([]);const [status,setStatus]=useState("");const [query,setQuery]=useState("");const [editor,setEditor]=useState<Coupon|null|"new">(null);const [barcode,setBarcode]=useState<Barcode|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(false);const [reload,setReload]=useState(0);const [page,setPage]=useState(1);const pageSize=8;
  const space=spaces.find(item=>item.id===spaceId)??spaces[0],token=session?.accessToken;
  useEffect(()=>{let active=true;async function load(){await Promise.resolve();if(!space?.id)return;setLoading(true);try{const data=demo?demoCoupons(space.id):await api.listCoupons(token!,space.id,status,query);if(active)setCoupons(data);}catch(reason){if(active)setError(reason instanceof Error?reason.message:"쿠폰을 불러오지 못했습니다.");}finally{if(active)setLoading(false)}}void load();return()=>{active=false}},[demo,query,reload,space?.id,status,token]);
  function replace(coupon:Coupon){setCoupons(current=>current.map(item=>item.id===coupon.id?coupon:item));}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!space)return;const form=new FormData(event.currentTarget);const input:CouponInput={title:String(form.get("title")),brand:String(form.get("brand")),description:String(form.get("description")),expiresAt:new Date(String(form.get("expiresAt"))).toISOString(),barcodeValue:String(form.get("barcodeValue")),barcodeFormat:String(form.get("barcodeFormat"))};try{if(demo)setEditor(null);else{if(editor==="new")await api.createCoupon(token!,space.id,input);else await api.updateCoupon(token!,(editor as Coupon).id,input);setEditor(null);setReload(value=>value+1)}}catch(reason){setError(reason instanceof Error?reason.message:"쿠폰을 저장하지 못했습니다.")}}
  async function action(coupon:Coupon,type:"claim"|"release"|"use"){try{if(demo){replace({...coupon,status:type==="claim"?"CLAIMED":type==="use"?"USED":"AVAILABLE",claimedBy:type==="release"?undefined:"demo",claimedByName:type==="release"?undefined:"김모아",barcodeAvailable:type!=="release"});return}const changed=type==="claim"?await api.claimCoupon(token!,coupon.id):type==="release"?await api.releaseCoupon(token!,coupon.id):await api.useCoupon(token!,coupon.id);replace(changed)}catch(reason){setError(reason instanceof Error?reason.message:"쿠폰 상태를 변경하지 못했습니다.")}}
  async function reveal(coupon:Coupon){try{setBarcode(demo?{couponId:coupon.id,value:"8801234567893",format:"EAN13",status:coupon.status}:await api.revealBarcode(token!,coupon.id))}catch(reason){setError(reason instanceof Error?reason.message:"바코드를 열지 못했습니다.")}}
  async function remove(coupon:Coupon){if(!window.confirm("쿠폰을 삭제할까요?"))return;try{if(!demo)await api.deleteCoupon(token!,coupon.id);setCoupons(current=>current.filter(item=>item.id!==coupon.id))}catch(reason){setError(reason instanceof Error?reason.message:"쿠폰을 삭제하지 못했습니다.")}}
  const safePage=Math.min(page,Math.max(1,Math.ceil(coupons.length/pageSize)));const visibleCoupons=coupons.slice((safePage-1)*pageSize,safePage*pageSize);
  return <section className={`${styles.card} ${styles.couponSection}`}><div className={styles.sharedToolbar}><div><h2>쿠폰함</h2><p>필요한 사람이 안전하게 선점하고 사용 상태를 함께 확인합니다.</p></div>{space?.role!=="VIEWER"&&<button className={styles.primaryButton} onClick={()=>setEditor("new")}>＋ 쿠폰 등록</button>}</div><div className={styles.filterBar}><select value={space?.id} onChange={event=>{setSpaceId(event.target.value);setPage(1)}}>{spaces.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="브랜드 또는 쿠폰 검색"/><select value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}><option value="">전체 상태</option>{Object.entries(statusLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>{error&&<p className={styles.error}>{error}</p>}{loading&&<p className={styles.empty}>쿠폰을 불러오는 중…</p>}<div className={styles.couponGrid}>{visibleCoupons.map(coupon=><article className={styles.couponCard} key={coupon.id} data-status={coupon.status}><header><span>{coupon.brand}</span><b>{statusLabel[coupon.status]}</b></header><div className={styles.couponIcon}>◇</div><h3>{coupon.title}</h3><p>{coupon.description||"함께 사용할 수 있는 공유 쿠폰"}</p><time>{new Date(coupon.expiresAt).toLocaleString("ko-KR")}까지</time>{coupon.claimedByName&&<small>{coupon.claimedByName} 님이 선점</small>}<footer>{coupon.status==="AVAILABLE"&&space?.role!=="VIEWER"&&<button className={styles.primaryButton} onClick={()=>action(coupon,"claim")}>내가 사용할게요</button>}{coupon.status==="CLAIMED"&&<><button onClick={()=>reveal(coupon)}>바코드 보기</button><button onClick={()=>action(coupon,"use")}>사용 완료</button><button onClick={()=>action(coupon,"release")}>선점 해제</button></>}{coupon.barcodeAvailable&&coupon.status!=="CLAIMED"&&<button onClick={()=>reveal(coupon)}>바코드</button>}{coupon.canEdit&&<button onClick={()=>setEditor(coupon)}>수정</button>}{coupon.canEdit&&<button className={styles.dangerButton} onClick={()=>remove(coupon)}>삭제</button>}</footer></article>)}</div><Pagination page={safePage} totalItems={coupons.length} pageSize={pageSize} onChange={setPage}/>{!loading&&coupons.length===0&&<p className={styles.empty}>등록된 쿠폰이 없습니다.</p>}{editor&&<CouponEditor coupon={editor==="new"?null:editor} onClose={()=>setEditor(null)} onSubmit={save}/>} {barcode&&<BarcodeModal barcode={barcode} onClose={()=>setBarcode(null)}/>}</section>
}
function CouponEditor({coupon,onClose,onSubmit}:{coupon:Coupon|null;onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+30);return <div className={styles.modalBackdrop}><div className={styles.modal}><button className={styles.closeButton} onClick={onClose}>×</button><p className={styles.eyebrow}>공유 쿠폰</p><h2>{coupon?"쿠폰 수정":"쿠폰 등록"}</h2><form className={styles.form} onSubmit={onSubmit}><label>브랜드<input required name="brand" maxLength={80} defaultValue={coupon?.brand}/></label><label>쿠폰 이름<input required name="title" maxLength={120} defaultValue={coupon?.title}/></label><label>설명<input name="description" maxLength={2000} defaultValue={coupon?.description}/></label><label>만료일<input required type="datetime-local" name="expiresAt" defaultValue={localInput(coupon?.expiresAt??tomorrow.toISOString())}/></label><label>바코드 값<input required name="barcodeValue" maxLength={500} placeholder={coupon?"보안을 위해 다시 입력해 주세요":"숫자 또는 코드"}/></label><label>바코드 형식<select name="barcodeFormat" defaultValue={coupon?.barcodeFormat??"CODE128"}><option>CODE128</option><option>EAN13</option></select></label><button className={styles.primaryButtonLarge}>저장</button></form></div></div>}
function BarcodeModal({barcode,onClose}:{barcode:Barcode;onClose:()=>void}){const canvas=useRef<HTMLCanvasElement>(null);useEffect(()=>{if(!canvas.current)return;const options={width:2,height:92,margin:12,displayValue:true,fontSize:16,background:"#ffffff",lineColor:"#151515"};const format=barcode.format==="EAN13"&&/^\d{12,13}$/.test(barcode.value)?"EAN13":"CODE128";try{JsBarcode(canvas.current,barcode.value,{...options,format});}catch{JsBarcode(canvas.current,barcode.value,{...options,format:"CODE128"});}},[barcode]);return <div className={styles.modalBackdrop}><div className={`${styles.modal} ${styles.barcodeModal}`}><button className={styles.closeButton} onClick={onClose}>×</button><p className={styles.eyebrow}>선점 사용자 전용</p><h2>쿠폰 바코드</h2><canvas ref={canvas} aria-label={`${barcode.format} 쿠폰 바코드`}/><code>{barcode.value}</code><small>{barcode.format} · 사용 후 반드시 사용 완료로 변경해 주세요.</small></div></div>}
function demoCoupons(spaceId:string):Coupon[]{const expiry=new Date();expiry.setDate(expiry.getDate()+7);return[{id:"demo-coupon",spaceId,title:"아메리카노 한 잔",brand:"Moa Cafe",description:"가족 누구나 사용 가능",expiresAt:expiry.toISOString(),barcodeFormat:"EAN13",status:"AVAILABLE",ownerId:"demo",barcodeAvailable:true,canEdit:true,version:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}]}
