"use client";

import { FormEvent, useEffect, useState } from "react";
import { api, AppNotification, AuthResult, NotificationPreferences } from "../lib/api";
import styles from "./CouponWithApp.module.css";
import { Pagination } from "./Pagination";

const defaults:NotificationPreferences={appNotifications:true,emailNotifications:false,eventReminders:true,postActivity:true,couponActivity:true};
export function SettingsView({session,demo,onSessionChange,onUnreadChange,onLogout,onDeleted}:{session:AuthResult|null;demo:boolean;onSessionChange:(session:AuthResult)=>void;onUnreadChange:(count:number)=>void;onLogout:()=>void;onDeleted:()=>void}){
  const [notifications,setNotifications]=useState<AppNotification[]>([]);const [preferences,setPreferences]=useState(defaults);const [error,setError]=useState("");const [message,setMessage]=useState("");const [page,setPage]=useState(1);const token=session?.accessToken;const pageSize=12;
  useEffect(()=>{let active=true;async function load(){await Promise.resolve();if(demo){const items=demoNotifications();setNotifications(items);onUnreadChange(items.filter(item=>!item.readAt).length);return}if(!token)return;try{const [items,prefs]=await Promise.all([api.listNotifications(token),api.getPreferences(token)]);if(active){setNotifications(items);setPreferences(prefs);onUnreadChange(items.filter(item=>!item.readAt).length)}}catch(reason){if(active)setError(reason instanceof Error?reason.message:"설정을 불러오지 못했습니다.")}}void load();return()=>{active=false}},[demo,onUnreadChange,token]);
  async function saveProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{const user=demo?{...session!.user,displayName:String(form.get("displayName")),timezone:String(form.get("timezone"))}:await api.updateProfile(token!,{displayName:String(form.get("displayName")),timezone:String(form.get("timezone"))});onSessionChange({...session!,user});setMessage("프로필을 저장했습니다.")}catch(reason){setError(reason instanceof Error?reason.message:"프로필을 저장하지 못했습니다.")}}
  async function savePreferences(next:NotificationPreferences){setPreferences(next);try{if(!demo)setPreferences(await api.updatePreferences(token!,next));setMessage("알림 설정을 저장했습니다.")}catch(reason){setError(reason instanceof Error?reason.message:"알림 설정을 저장하지 못했습니다.")}}
  async function read(item:AppNotification){if(item.readAt)return;try{const changed=demo?{...item,readAt:new Date().toISOString()}:await api.readNotification(token!,item.id);setNotifications(current=>{const next=current.map(value=>value.id===item.id?changed:value);onUnreadChange(next.filter(value=>!value.readAt).length);return next})}catch(reason){setError(reason instanceof Error?reason.message:"알림을 읽음 처리하지 못했습니다.")}}
  async function readAll(){try{if(!demo)await api.readAllNotifications(token!);setNotifications(current=>current.map(item=>({...item,readAt:item.readAt??new Date().toISOString()})));onUnreadChange(0)}catch(reason){setError(reason instanceof Error?reason.message:"알림을 처리하지 못했습니다.")}}
  async function deleteAccount(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!window.confirm("계정을 삭제하면 모든 공간에서 즉시 로그아웃됩니다. 계속할까요?"))return;const form=new FormData(event.currentTarget);try{if(!demo)await api.deleteAccount(token!,String(form.get("password")));onDeleted()}catch(reason){setError(reason instanceof Error?reason.message:"계정을 삭제하지 못했습니다.")}}
  const toggle=(key:keyof NotificationPreferences)=><label className={styles.settingToggle}><span><strong>{settingText[key][0]}</strong><small>{settingText[key][1]}</small></span><input type="checkbox" checked={preferences[key]} onChange={event=>void savePreferences({...preferences,[key]:event.target.checked})}/></label>;
  const visibleNotifications=notifications.slice((page-1)*pageSize,page*pageSize);
  return <div className={styles.settingsGrid}><section className={styles.card}><div className={styles.sectionHeader}><div><h2>앱 내 알림</h2><p>최근 알림 {notifications.length}개</p></div><button onClick={readAll}>모두 읽음</button></div><div className={styles.notificationList}>{notifications.length===0?<p className={styles.empty}>새 알림이 없습니다.</p>:visibleNotifications.map(item=><button key={item.id} data-read={Boolean(item.readAt)} onClick={()=>read(item)}><i/><span><strong>{item.title}</strong><small>{item.message}</small><time>{new Date(item.createdAt).toLocaleString("ko-KR")}</time></span></button>)}</div><Pagination page={page} totalItems={notifications.length} pageSize={pageSize} onChange={setPage}/></section><div className={styles.settingsSide}><section className={styles.card}><div className={styles.sectionHeader}><div><h2>프로필</h2><p>다른 구성원에게 보이는 정보</p></div><button type="button" onClick={onLogout}>로그아웃</button></div><form className={styles.form} onSubmit={saveProfile}><label>이름<input required name="displayName" maxLength={40} defaultValue={session?.user.displayName}/></label><label>시간대<select name="timezone" defaultValue={session?.user.timezone??"Asia/Seoul"}><option>Asia/Seoul</option><option>UTC</option><option>America/New_York</option><option>Europe/London</option></select></label><button className={styles.primaryButtonLarge}>프로필 저장</button></form></section><section className={styles.card}><div className={styles.sectionHeader}><div><h2>알림 설정</h2><p>이메일은 로컬 Mailpit 수신함에서 확인합니다.</p></div></div><div className={styles.settingList}>{toggle("appNotifications")}{toggle("emailNotifications")}{toggle("eventReminders")}{toggle("postActivity")}{toggle("couponActivity")}</div></section><section className={`${styles.card} ${styles.dangerZone}`}><h2>계정 삭제</h2><p>소유한 공간을 보관 처리하고 개인정보를 익명화합니다.</p><form className={styles.form} onSubmit={deleteAccount}><label>현재 비밀번호<input required name="password" type="password"/></label><button className={styles.dangerOutlineButton}>계정 영구 삭제</button></form></section>{message&&<p className={styles.success}>{message}</p>}{error&&<p className={styles.error}>{error}</p>}</div></div>
}
const settingText:Record<keyof NotificationPreferences,[string,string]>={appNotifications:["앱 내 알림","MoaDay 안에서 새 소식을 표시합니다."],emailNotifications:["이메일 알림","로컬 메일 수신함에도 알림을 보냅니다."],eventReminders:["일정과 참석","일정 초대와 참석 응답을 알립니다."],postActivity:["공유글과 댓글","새 글과 댓글 소식을 알립니다."],couponActivity:["쿠폰 활동","등록, 선점과 사용 소식을 알립니다."]};
function demoNotifications():AppNotification[]{return[{id:"notice-1",type:"EVENT_INVITATION",title:"새 일정 초대",message:"가족 저녁 일정에 초대되었습니다.",createdAt:new Date().toISOString()},{id:"notice-2",type:"COUPON_CREATED",title:"새 공유 쿠폰",message:"아메리카노 쿠폰이 등록되었습니다.",readAt:new Date().toISOString(),createdAt:new Date().toISOString()}]}
