"use client";
/* eslint-disable @next/next/no-img-element */

import { FormEvent, useEffect, useState } from "react";
import { api, AuthResult, PostAttachment, PostComment, PostDetail, SharedPost, Space } from "../lib/api";
import { Pagination } from "./Pagination";
import styles from "./CouponWithApp.module.css";

export function SharedView({ spaces, session, demo }: { spaces: Space[]; session: AuthResult | null; demo: boolean }) {
  const [spaceId,setSpaceId]=useState(spaces[0]?.id??""); const [posts,setPosts]=useState<SharedPost[]>([]);
  const [query,setQuery]=useState(""); const [tag,setTag]=useState(""); const [pinned,setPinned]=useState(false);
  const [detail,setDetail]=useState<PostDetail|null>(null); const [editor,setEditor]=useState<SharedPost|null|"new">(null);
  const [editingComment,setEditingComment]=useState<PostComment|null>(null);
  const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [reload,setReload]=useState(0);
  const [page,setPage]=useState(1); const pageSize=9;
  const space=spaces.find(item=>item.id===spaceId)??spaces[0]; const token=session?.accessToken;

  useEffect(()=>{let active=true;async function load(){await Promise.resolve();if(!space?.id)return;setLoading(true);try{
    const loaded=demo?demoPosts(space.id):await api.listPosts(token!,space.id,query,tag,pinned);if(active)setPosts(loaded);
  }catch(reason){if(active)setError(reason instanceof Error?reason.message:"공유글을 불러오지 못했습니다.");}finally{if(active)setLoading(false);}}void load();return()=>{active=false};},[demo,pinned,query,reload,space?.id,tag,token]);

  async function openPost(post:SharedPost){try{setDetail(demo?{post,comments:[]} : await api.getPost(token!,post.id));setError("");}catch(reason){setError(reason instanceof Error?reason.message:"게시글을 열지 못했습니다.");}}
  async function savePost(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!space)return;const form=new FormData(event.currentTarget);const input={title:String(form.get("title")),content:String(form.get("content")),tags:String(form.get("tags")).split(",").map(value=>value.trim()).filter(Boolean)};try{
    let saved:PostDetail;if(demo){const post={id:editor==="new"?crypto.randomUUID():(editor as SharedPost).id,spaceId:space.id,...input,pinned:false,authorId:"demo",authorName:"김모아",attachments:[],commentCount:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),canEdit:true};saved={post,comments:[]};}
    else saved=editor==="new"?await api.createPost(token!,space.id,input):await api.updatePost(token!,(editor as SharedPost).id,input);
    const file=form.get("file");if(!demo&&file instanceof File&&file.size>0)await api.uploadAttachment(token!,saved.post.id,file);
    setEditor(null);setDetail(null);setReload(value=>value+1);
  }catch(reason){setError(reason instanceof Error?reason.message:"게시글을 저장하지 못했습니다.");}}
  async function togglePin(post:SharedPost){try{if(!demo)await api.pinPost(token!,post.id,!post.pinned);setPosts(current=>current.map(item=>item.id===post.id?{...item,pinned:!item.pinned}:item));if(detail?.post.id===post.id)setDetail({...detail,post:{...detail.post,pinned:!post.pinned}});}catch(reason){setError(reason instanceof Error?reason.message:"고정 상태를 바꾸지 못했습니다.");}}
  async function deletePost(post:SharedPost){if(!window.confirm("이 게시글을 삭제할까요?"))return;try{if(!demo)await api.deletePost(token!,post.id);setDetail(null);setReload(value=>value+1);}catch(reason){setError(reason instanceof Error?reason.message:"게시글을 삭제하지 못했습니다.");}}
  async function addComment(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!detail)return;const form=new FormData(event.currentTarget),content=String(form.get("content"));try{const comment=demo?demoComment(content):await api.addComment(token!,detail.post.id,content);setDetail({...detail,comments:[...detail.comments,comment]});event.currentTarget.reset();}catch(reason){setError(reason instanceof Error?reason.message:"댓글을 저장하지 못했습니다.");}}
  function editComment(comment:PostComment){setEditingComment(comment);}
  async function saveComment(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editingComment)return;const content=String(new FormData(event.currentTarget).get("content")).trim();if(!content)return;try{const changed=demo?{...editingComment,content}:await api.updateComment(token!,editingComment.id,content);setDetail(current=>current?{...current,comments:current.comments.map(item=>item.id===editingComment.id?changed:item)}:current);setEditingComment(null);}catch(reason){setError(reason instanceof Error?reason.message:"댓글을 수정하지 못했습니다.");}}
  async function deleteComment(comment:PostComment){if(!window.confirm("댓글을 삭제할까요?"))return;try{if(!demo)await api.deleteComment(token!,comment.id);setDetail(current=>current?{...current,comments:current.comments.filter(item=>item.id!==comment.id)}:current);}catch(reason){setError(reason instanceof Error?reason.message:"댓글을 삭제하지 못했습니다.");}}
  const canManage=space?.role==="OWNER"||space?.role==="ADMIN";
  const safePage=Math.min(page,Math.max(1,Math.ceil(posts.length/pageSize)));const visiblePosts=posts.slice((safePage-1)*pageSize,safePage*pageSize);
  return <section className={`${styles.card} ${styles.sharedCard}`}>
    <div className={styles.sharedToolbar}><div><h2>공유함</h2><p>글, 파일과 대화를 공간별로 모아 둡니다.</p></div>{space?.role!=="VIEWER"&&<button className={styles.primaryButton} onClick={()=>setEditor("new")}>＋ 새 글</button>}</div>
    <div className={styles.filterBar}><select aria-label="공간" value={space?.id} onChange={event=>{setSpaceId(event.target.value);setDetail(null);setPage(1)}}>{spaces.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="제목과 내용 검색" aria-label="게시글 검색"/><input value={tag} onChange={event=>{setTag(event.target.value);setPage(1)}} placeholder="태그 검색" aria-label="태그 검색"/><label><input type="checkbox" checked={pinned} onChange={event=>{setPinned(event.target.checked);setPage(1)}}/> 고정 글만</label></div>
    {loading&&<p className={styles.empty}>공유글을 불러오는 중…</p>}{error&&<p className={styles.error}>{error}</p>}
    <div className={styles.postGrid}>{visiblePosts.map(post=><article key={post.id} className={styles.postCard} onClick={()=>openPost(post)}><div className={styles.postMeta}><span>{post.authorName}</span><time>{new Date(post.updatedAt).toLocaleDateString("ko-KR")}</time>{post.pinned&&<b>고정</b>}</div><h3>{post.title}</h3><p>{post.content}</p><div className={styles.tagRow}>{post.tags.map(value=><span key={value}>#{value}</span>)}</div><footer><span>📎 {post.attachments.length}</span><span>댓글 {post.commentCount}</span>{canManage&&<button type="button" onClick={event=>{event.stopPropagation();void togglePin(post)}}>{post.pinned?"고정 해제":"고정"}</button>}</footer></article>)}</div>
    <Pagination page={safePage} totalItems={posts.length} pageSize={pageSize} onChange={setPage}/>
    {!loading&&posts.length===0&&<p className={styles.empty}>조건에 맞는 공유글이 없습니다.</p>}
    {editor&&<PostEditor post={editor==="new"?null:editor} onClose={()=>setEditor(null)} onSubmit={savePost}/>} 
    {detail&&<PostDetailModal detail={detail} canManage={canManage} canComment={space?.role!=="VIEWER"} demo={demo} token={token} onClose={()=>setDetail(null)} onEdit={()=>{setEditor(detail.post);setDetail(null)}} onDelete={()=>deletePost(detail.post)} onPin={()=>togglePin(detail.post)} onAddComment={addComment} onEditComment={editComment} onDeleteComment={deleteComment}/>} 
    {editingComment&&<CommentEditor comment={editingComment} onClose={()=>setEditingComment(null)} onSubmit={saveComment}/>} 
  </section>;
}

function PostEditor({post,onClose,onSubmit}:{post:SharedPost|null;onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){return <div className={styles.modalBackdrop}><div className={`${styles.modal} ${styles.postModal}`}><button className={styles.closeButton} onClick={onClose}>×</button><p className={styles.eyebrow}>{post?"공유글 편집":"새로운 공유"}</p><h2>{post?post.title:"공유글 작성"}</h2><form className={styles.form} onSubmit={onSubmit}><label>제목<input required name="title" maxLength={160} defaultValue={post?.title}/></label><label>내용<textarea required name="content" maxLength={10000} defaultValue={post?.content} placeholder="함께 알아야 할 내용을 적어 주세요."/></label><label>태그<input name="tags" defaultValue={post?.tags.join(", ")} placeholder="여행, 준비물, 가족"/></label><label>첨부파일<input name="file" type="file"/></label><button className={styles.primaryButtonLarge}>{post?"변경 저장":"공유하기"}</button></form></div></div>}
function CommentEditor({comment,onClose,onSubmit}:{comment:PostComment;onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){return <div className={styles.modalBackdrop}><div className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="comment-editor-title"><button type="button" className={styles.closeButton} aria-label="닫기" onClick={onClose}>×</button><p className={styles.eyebrow}>댓글 편집</p><h2 id="comment-editor-title">댓글 수정</h2><form className={styles.form} onSubmit={onSubmit}><label>내용<textarea required autoFocus name="content" maxLength={2000} defaultValue={comment.content}/></label><button className={styles.primaryButtonLarge}>변경 저장</button></form></div></div>}
function PostDetailModal({detail,canManage,canComment,demo,token,onClose,onEdit,onDelete,onPin,onAddComment,onEditComment,onDeleteComment}:{detail:PostDetail;canManage:boolean;canComment:boolean;demo:boolean;token?:string;onClose:()=>void;onEdit:()=>void;onDelete:()=>void;onPin:()=>void;onAddComment:(event:FormEvent<HTMLFormElement>)=>void;onEditComment:(comment:PostComment)=>void;onDeleteComment:(comment:PostComment)=>void}){const post=detail.post;return <div className={styles.modalBackdrop}><div className={`${styles.modal} ${styles.postModal}`}><button className={styles.closeButton} onClick={onClose}>×</button><div className={styles.postMeta}><span>{post.authorName}</span><time>{new Date(post.updatedAt).toLocaleString("ko-KR")}</time>{post.pinned&&<b>고정</b>}</div><h2>{post.title}</h2><div className={styles.postBody}>{post.content}</div><div className={styles.tagRow}>{post.tags.map(tag=><span key={tag}>#{tag}</span>)}</div>{post.attachments.length>0&&<div className={styles.attachmentList}>{post.attachments.map(file=>file.contentType.startsWith("image/")&&!file.contentType.includes("svg")?<ImageAttachment key={file.id} file={file} token={token} demo={demo}/>:<button key={file.id} onClick={()=>{if(!demo&&token)void api.downloadAttachment(token,file)}}>📎 {file.originalName} <small>{Math.ceil(file.sizeBytes/1024)}KB</small></button>)}</div>}<div className={styles.postActions}>{canManage&&<button onClick={onPin}>{post.pinned?"고정 해제":"상단 고정"}</button>}{post.canEdit&&<><button onClick={onEdit}>수정</button><button className={styles.dangerButton} onClick={onDelete}>삭제</button></>}</div><section className={styles.commentSection}><h3>댓글 {detail.comments.length}</h3>{detail.comments.map(comment=><div className={styles.commentRow} key={comment.id}><span className={styles.avatar}>{comment.authorName.slice(0,1)}</span><div><strong>{comment.authorName}</strong><p>{comment.content}</p><small>{new Date(comment.createdAt).toLocaleString("ko-KR")}</small></div>{comment.canEdit&&<span><button onClick={()=>onEditComment(comment)}>수정</button><button onClick={()=>onDeleteComment(comment)}>삭제</button></span>}</div>)}{canComment&&<form className={styles.commentForm} onSubmit={onAddComment}><input required name="content" maxLength={2000} placeholder="댓글을 입력하세요."/><button className={styles.primaryButton}>등록</button></form>}</section></div></div>}
function ImageAttachment({file,token,demo}:{file:PostAttachment;token?:string;demo:boolean}){const [url,setUrl]=useState("");const [open,setOpen]=useState(false);useEffect(()=>{if(demo||!token)return;let disposed=false;let objectUrl="";void api.attachmentBlob(token,file.id).then(blob=>{if(disposed)return;objectUrl=URL.createObjectURL(blob);setUrl(objectUrl)}).catch(()=>setUrl(""));return()=>{disposed=true;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[demo,file.id,token]);if(!url)return <button onClick={()=>{if(!demo&&token)void api.downloadAttachment(token,file)}}>📎 {file.originalName} <small>{Math.ceil(file.sizeBytes/1024)}KB</small></button>;return <><button type="button" className={styles.imageAttachment} onClick={()=>setOpen(true)}><img src={url} alt={file.originalName}/><span>{file.originalName}<small>{Math.ceil(file.sizeBytes/1024)}KB · 크게 보기</small></span></button>{open&&<div className={styles.imageLightbox} role="dialog" aria-modal="true" aria-label={`${file.originalName} 이미지 미리보기`} onClick={()=>setOpen(false)}><button type="button" aria-label="이미지 닫기" onClick={()=>setOpen(false)}>×</button><img src={url} alt={file.originalName} onClick={event=>event.stopPropagation()}/></div>}</>}
function demoPosts(spaceId:string):SharedPost[]{return [{id:"demo-post",spaceId,title:"여름휴가 준비물",content:"여권, 충전기, 상비약을 출발 전날까지 확인해 주세요.",pinned:true,authorId:"demo",authorName:"김모아",tags:["여행","준비물"],attachments:[],commentCount:2,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),canEdit:true}]}
function demoComment(content:string):PostComment{return{id:crypto.randomUUID(),authorId:"demo",authorName:"김모아",content,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),canEdit:true}}
